# Size represents the percent of traffic you want for each test
# The total of all sizes should equal 100% of traffic.
# It's easiest to think of it as being based out of 10 or 100.
# Right now, we are running a 50/50 traffic split
BASELINE:
  description: The baseline. This is a version running the default code.
  size: 5
test1:
  description: Just a simple change to the intro text on the index page
  size: 5
